services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_MODEL=gemma
    depends_on:
      - ollama
    volumes:
      - .:/app
    networks:
      - novin-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 7G
        reservations:
          memory: 6.5G
    environment:
      - OLLAMA_MAX_LOADED_MODELS=1
    networks:
      - novin-network

volumes:
  ollama_data:
    driver: local

networks:
  novin-network:
    driver: bridge 