apiVersion: skaffold/v2beta29
kind: Config

build:
  artifacts:
  - image: novin-yar
    context: .
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    sha256: {}

deploy:
  kubectl:
    manifests:
      - k8s/overlays/dev
    flags:
      global:
        - --namespace=novin-yar-dev

profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
          - k8s/overlays/dev
        flags:
          global:
            - --namespace=novin-yar-dev

  - name: prod
    deploy:
      kubectl:
        manifests:
          - k8s/overlays/prod
        flags:
          global:
            - --namespace=novin-yar-prod 